import cgi
import datetime

print("<!DOCTYPE html>")
print("<html lang='en'>")
print("<head>")
print("    <meta charset='UTF-8'>")
print("    <meta name='viewport' content='width=device-width, initial-scale=1.0'>")
print("    <title>Success</title>")
print("    <style>")
print("        body {")
print("            font-family: Arial, sans-serif;")
print("            background-color: #f0f0f0;")
print("            margin: 0;")
print("            padding: 0;")
print("            display: flex;")
print("            justify-content: center;")
print("            align-items: center;")
print("            flex-direction: column;")
print("            height: 100vh;")
print("        }")
print("        .container {")
print("            background-color: #fff;")
print("            padding: 20px;")
print("            border-radius: 8px;")
print("            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);")
print("            margin-bottom: 20px;")
print("            text-align: center;")
print("            width: 80%;")
print("            max-width: 600px;")
print("        }")
print("        h1 {")
print("            margin-bottom: 20px;")
print("        }")
print("        h2 {")
print("            margin: 20px 0;")
print("        }")
print("        button {")
print("            background-color: #007bff;")
print("            color: #fff;")
print("            border: none;")
print("            padding: 10px 20px;")
print("            border-radius: 4px;")
print("            cursor: pointer;")
print("        }")
print("        button:hover {")
print("            background-color: #0056b3;")
print("        }")
print("    </style>")
print("</head>")
print("<body>")
print("    <div class='container'>")
print("        <h1>Success!</h1>")
print("        <p>Your action was successful.</p>")
print("        <h2>Current time: {}</h2>".format(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")))
print("        <a href='/index.html'>Go back</a>")
print("    </div>")
print("</body>")
print("</html>")
